name: cafe_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.4.0
  provider: ^5.0.0
  path_provider: ^2.0.2
  flutter_spinkit: ^5.1.0
  community_material_icon: ^5.8.55-null-safe
  hive: ^2.0.4
  firebase_core: ^1.4.0
  internet_connection_checker: ^0.0.1+2
  url_launcher: ^6.0.9
  lint: ^1.6.0
  flutter_launcher_icons: ^0.9.2
  google_fonts: ^2.1.0
  multiple_stream_builder: ^2.0.0
  flutter_credit_card: ^2.0.0
  #flutter_html: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: assets/cafe.jpg

flutter:
  uses-material-design: true
  assets:
    - assets/cafe.jpg
    - assets/cafe2.jpg
    - assets/cafeback1.jpg
    - assets/cafeback2.jpg
    - assets/beans.jpg
  fonts:
    - family: Galada
      fonts:
        - asset: fonts/Galada-Regular.ttf
    - family: Orbitron
      fonts:
        - asset: fonts/Orbitron-Regular.ttf
    - family: Righteous
      fonts:
        - asset: fonts/Righteous-Regular.ttf
    - family: Satisfy
      fonts:
        - asset: fonts/Satisfy-Regular.ttf
